spring.application.name=online-book-store

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

server.servlet.context-path=/api

jwt.expiration=300000
jwt.secret=rewgfe3wfgwegw32rf23f2????57?5??56576??7?67

spring.docker.compose.file=docker-compose-dev.yml
